openapi: 3.2.0
info:
  description: Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.
  title: Cohesity REST Internal API
  version: '2.0'
servers:
- url: /v2
tags:
- name: Internal
paths:
  /refresh-bulletin-board:
    post:
      description: Refresh bulletin board from Helios.
      tags:
      - Internal
      summary: Refresh bulletin board from Helios
      operationId: RefreshBulletinBoard
      responses:
        '204':
          $ref: '#/components/responses/NoContentResponse'
        default:
          $ref: '#/components/responses/ErrorResponse'
      security:
      - APIKeyHeader: []
components:
  responses:
    NoContentResponse:
      description: No Content
    ErrorResponse:
      description: Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    Error:
      description: Specifies the error object with error code and a message.
      type: object
      title: Error.
      properties:
        errorCode:
          description: Specifies the error code.
          type:
          - string
          - 'null'
          x-order: 0
        message:
          description: Specifies the error message.
          type:
          - string
          - 'null'
          x-order: 1
  securitySchemes:
    APIKeyHeader:
      in: header
      name: apiKey
      type: apiKey
